version: '3.3'
services:
  #mongodb services
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  
  #tourismapp services
  tourismapp:
    restart: unless-stopped
    build: .
##    Uncomment this if you want to expose app too.
##    ports:
##    - 3000:${WEBAPP_PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_network
    environment:
      - MODE=DEV
      - SERVICE_NAME=tourismapp
      - MONGO_URL=mongodb://mongo_db:27017/tourismapp
    depends_on:
      - mongo_db
  
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

volumes:
  mongo_db: {}

networks:
  node_network: