name: CI CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Reset Permissions before deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod -R 755 /tourismapp
            sudo chown -R username:username /tourismapp
            sudo setfacl -R -m u:www-data:rwx /tourismapp 

      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
          FINGERPRINT: ${{ secrets.PUBLIC_KEY }}
        with:
          source: "*"
          target: "/tourismapp"

      - name: Reset Permissions after deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.PUBLIC_KEY }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            sudo chmod -R 755 /tourismapp
            sudo chown -R www-data:www-data /tourismapp
            sudo setfacl -R -m u:username:rwx /tourismapp