name: CI CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Reset Permissions before deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            sudo chmod -R 755 /apss
            sudo chown -R ligabayu:ligabayu /apss
            sudo setfacl -R -m u:www-data:rwx /apss 

      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          PORT: 22
        with:
          source: "*"
          target: "/apss"

      - name: Reset Permissions after deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            sudo chmod -R 777 /apss
            sudo chown -R www-data:www-data /apss
            sudo setfacl -R -m u:username:rwx /apss